version: '3.9'
services:
  web:
    build: .
    working_dir: /app
    environment:
      FLASK_APP: flaskr         # point to the flaskr app package
      FLASK_ENV: development    # optional, e.g. development mode
    ports:
      - "5000:5000"             # map host port 5000 to container port 5000
    volumes:
      - .:/app                  # mount code for live changes
    command: flask run --host=0.0.0.0 --port=5000